# Generated by Django 4.2.11 on 2024-07-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PowerPlantInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("gppd_idnr", models.CharField(max_length=12)),
                ("capacity_mw", models.FloatField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("primary_fuel", models.CharField(max_length=50)),
                ("year_of_capacity_data", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "PowerPlantInfo",
            },
        ),
    ]
